create table if not exists public.orcamentos (
  id bigint generated by default as identity primary key,
  cliente_id bigint references public.cadastro(id) on delete set null,
  cliente_nome text not null,
  data_reserva date not null,
  data_retirada date not null,
  valor_total numeric(12, 2) not null default 0,
  valor_frete numeric(12, 2) not null default 0,
  valor_desconto numeric(12, 2) not null default 0,
  adiantamento numeric(12, 2) not null default 0,
  saldo_restante numeric(12, 2) not null default 0,
  observacoes text,
  status text not null default 'Aberto',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.orcamentos
  add column if not exists valor_frete numeric(12, 2) not null default 0;

alter table public.orcamentos
  add column if not exists valor_desconto numeric(12, 2) not null default 0;

create table if not exists public.orcamento_itens (
  id bigint generated by default as identity primary key,
  orcamento_id bigint not null references public.orcamentos(id) on delete cascade,
  estoque_id uuid references public.estoque(id) on delete set null,
  item text not null,
  codigo_item text,
  quantidade integer not null default 1 check (quantidade > 0),
  valor_unitario numeric(12, 2) not null default 0,
  valor_total numeric(12, 2) not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists idx_orcamentos_cliente_id
  on public.orcamentos(cliente_id);

create index if not exists idx_orcamentos_data_reserva
  on public.orcamentos(data_reserva);

create index if not exists idx_orcamento_itens_orcamento_id
  on public.orcamento_itens(orcamento_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_orcamentos_updated_at on public.orcamentos;

create trigger set_orcamentos_updated_at
before update on public.orcamentos
for each row
execute function public.set_updated_at();

alter table public.orcamentos enable row level security;
alter table public.orcamento_itens enable row level security;

drop policy if exists "Permitir leitura orcamentos" on public.orcamentos;
drop policy if exists "Permitir inserir orcamentos" on public.orcamentos;
drop policy if exists "Permitir atualizar orcamentos" on public.orcamentos;
drop policy if exists "Permitir deletar orcamentos" on public.orcamentos;

create policy "Permitir leitura orcamentos"
on public.orcamentos for select
to anon, authenticated
using (true);

create policy "Permitir inserir orcamentos"
on public.orcamentos for insert
to anon, authenticated
with check (true);

create policy "Permitir atualizar orcamentos"
on public.orcamentos for update
to anon, authenticated
using (true)
with check (true);

create policy "Permitir deletar orcamentos"
on public.orcamentos for delete
to anon, authenticated
using (true);

drop policy if exists "Permitir leitura orcamento_itens" on public.orcamento_itens;
drop policy if exists "Permitir inserir orcamento_itens" on public.orcamento_itens;
drop policy if exists "Permitir atualizar orcamento_itens" on public.orcamento_itens;
drop policy if exists "Permitir deletar orcamento_itens" on public.orcamento_itens;

create policy "Permitir leitura orcamento_itens"
on public.orcamento_itens for select
to anon, authenticated
using (true);

create policy "Permitir inserir orcamento_itens"
on public.orcamento_itens for insert
to anon, authenticated
with check (true);

create policy "Permitir atualizar orcamento_itens"
on public.orcamento_itens for update
to anon, authenticated
using (true)
with check (true);

create policy "Permitir deletar orcamento_itens"
on public.orcamento_itens for delete
to anon, authenticated
using (true);
